https://towardsdatascience.com/reinforcement-learning-implement-tictactoe-189582bea542

In [17]:
import numpy as np

In [109]:
class TicTacToe():
    def __init__(self,board_size):
        self.board_size=board_size
        self.board=np.zeros((self.board_size,self.board_size))
        self.winning_condition=False
        
        
    def new_board_dict(self):
        self.visited_dict={}
        for j in range(0,self.board_size):
            for i in range(0,self.board_size):
                self.visited_dict[(j,i)]=False
                
    def row_win_check(self,player):
        if player=='player1':
            for ind in range(0,self.board_size):
                if np.all(self.board[ind,:]==1):
                    self.winning_condition=True
                    self.winner='player1'
                    
        if player=='player2':
            for ind in range(0,self.board_size):
                if np.all(self.board[ind,:]==2):
                    self.winning_condition=True
                    self.winner='player2'
                    
    def column_win_check(self,player):
        if player=='player1':
            for ind in range(0,self.board_size):
                if np.all(self.board[:,ind]==1):
                    self.winning_condition=True
                    self.winner='player1'
                    
        if player=='player2':
            for ind in range(0,self.board_size):
                if np.all(self.board[:,ind]==2):
                    self.winning_condition=True
                    self.winner='player2'
                    
    def diag_win_check(self,player):
        diag_lst=[]
        if player=='player1':
            for ind in range(self.board_size):
                diag_lst.append(self.board[ind,ind])
            if np.all(diag_lst==1):
                self.winning_condition=True
                self.winner='player1'
        diag_lst=[]
        if player=='player2':
            for ind in range(self.board_size):
                diag_lst.append(self.board[ind,ind])
            if np.all(diag_lst==2):
                self.winning_condition=True
                self.winner='player2'
                
    
    def check_winning_condition(self,player):
        if player=='player1':
            self.row_win_check('player1')
            self.column_win_check('player1')
            self.diag_win_check('player1')
        if player=='player2':
            self.row_win_check('player2')
            self.column_win_check('player2')
            self.diag_win_check('player2')
    
    
    def random_policy(self):
        not_marked_lst=[k for (k,v) in self.visited_dict.items() if v==False]
        if len(not_marked_lst)==1:
            return not_marked_lst[0]
        elif len(not_marked_lst)==0:
            self.winning_condition=True
            random_action=0
            return random_action
        random_action=not_marked_lst[np.random.randint(0,len(not_marked_lst),1)[0]]
        return random_action

    
    def update_board(self,action,player):
        if player=='player1':
            self.board[action[0],action[1]]=1
        elif player=='player2':
            self.board[action[0],action[1]]=2
        
    def one_game(self):
        self.board=np.zeros((self.board_size,self.board_size))
        self.new_board_dict()
        while self.winning_condition!=True:
            player1_action=self.random_policy()
            self.visited_dict[player1_action]=True
            self.update_board(player1_action,'player1')
            self.check_winning_condition('player1')
            if self.winning_condition==True:
                print('Player1 won!')
                print(self.board)
                return 1
            player2_action=self.random_policy()
            if player2_action!=0:
                self.visited_dict[player2_action]=True 
                self.update_board(player2_action,'player2')
                self.check_winning_condition('player2')
                if self.winning_condition==True:
                    print('Player2 won!')
                    print(self.board)
                    return 2
            if np.all(self.board!=0):
                self.winning_condition=True
                print('It was a tie!')
                print(self.board)
                return 3
        #3 means tie
            
        

In [110]:
tic_tac_toe=TicTacToe(3)
tic_tac_toe.one_game()

It was a tie!
[[1. 2. 2.]
 [2. 1. 1.]
 [2. 1. 1.]]


3